# Generated by Django 5.0 on 2025-08-13 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashuser', '0005_unidaddemedida'),
        ('platos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentoplato',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='dashuser.unidaddemedida'),
            preserve_default=False,
        ),
    ]
