# Generated by Django 5.0 on 2025-08-14 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashuser', '0008_alimento_trazas'),
        ('platos', '0002_alimentoplato_unidad_medida'),
        ('super', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='salsas/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super.centros')),
            ],
            options={
                'verbose_name': 'Salsa',
                'verbose_name_plural': 'Salsas',
                'unique_together': {('nombre', 'centro')},
            },
        ),
        migrations.CreateModel(
            name='AlimentoSalsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notas', models.TextField(blank=True, null=True)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashuser.alimento')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super.centros')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashuser.unidaddemedida')),
                ('salsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='platos.salsa')),
            ],
            options={
                'verbose_name': 'Ingrediente de Salsa',
                'verbose_name_plural': 'Ingredientes de Salsa',
                'unique_together': {('salsa', 'alimento')},
            },
        ),
    ]
