# Generated by Django 5.2.5 on 2025-08-31 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0004_plato_salsa'),
        ('super', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtiquetaPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso real en gramos', max_digits=6)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('energia', models.DecimalField(decimal_places=2, max_digits=8)),
                ('carbohidratos', models.DecimalField(decimal_places=2, max_digits=8)),
                ('proteinas', models.DecimalField(decimal_places=2, max_digits=8)),
                ('grasas', models.DecimalField(decimal_places=2, max_digits=8)),
                ('azucares', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sal_mg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fibra', models.DecimalField(decimal_places=2, max_digits=8)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super.centros')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platos.plato')),
            ],
            options={
                'verbose_name': 'Etiqueta de Plato',
                'verbose_name_plural': 'Etiquetas de Platos',
            },
        ),
    ]
