# Generated by Django 5.0 on 2025-09-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0005_etiquetaplato'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código único para el plato', max_length=10, null=True, unique=True),
        ),
    ]
