# Generated by Django 5.0 on 2025-09-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0006_plato_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiquetaplato',
            name='lote',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
