# Generated by Django 5.0 on 2025-09-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0007_etiquetaplato_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='vida_util',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Número de días que se suman a la fecha de producción para calcular la caducidad', null=True),
        ),
        migrations.AlterField(
            model_name='plato',
            name='codigo',
            field=models.CharField(help_text='Código único para el plato', max_length=10, unique=True),
        ),
    ]
