# Generated by Django 5.0 on 2025-09-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0008_plato_vida_util_alter_plato_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiquetaplato',
            name='caducidad',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='etiquetaplato',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
