# Generated by Django 5.2.5 on 2025-09-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0009_etiquetaplato_caducidad_alter_etiquetaplato_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiquetaplato',
            name='impresa',
            field=models.BooleanField(default=False),
        ),
    ]
