# Generated by Django 5.2.5 on 2025-09-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0010_etiquetaplato_impresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiquetaplato',
            name='lote',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
