# Generated by Django 5.2.5 on 2025-09-19 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0011_alter_etiquetaplato_lote'),
        ('super', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosNuticionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energia_kj', models.DecimalField(decimal_places=2, help_text='Energía en Kj por 100g', max_digits=8)),
                ('grasas_totales', models.DecimalField(decimal_places=2, help_text='Grasas totales en g por 100g', max_digits=8)),
                ('grasas_saturadas', models.DecimalField(decimal_places=2, help_text='Grasas saturadas en g por 100g', max_digits=8)),
                ('hidratosdecarbono', models.DecimalField(decimal_places=2, help_text='Hidratos de carbono en g por 100g', max_digits=8)),
                ('azucares', models.DecimalField(decimal_places=2, help_text='Azúcares en g por 100g', max_digits=8)),
                ('proteinas', models.DecimalField(decimal_places=2, help_text='Proteinas en g por 100g', max_digits=8)),
                ('sal', models.DecimalField(decimal_places=2, help_text='Sal en g por 100g', max_digits=8)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super.centros')),
                ('plato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutricion', to='platos.plato')),
            ],
            options={
                'verbose_name': 'Datos Nutricionales',
                'verbose_name_plural': 'Datos Nutricionales',
            },
        ),
    ]
