# Generated by Django 5.2.5 on 2025-09-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0012_datosnuticionales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosnuticionales',
            name='azucares',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Azúcares en g por 100g', max_digits=6),
        ),
        migrations.AlterField(
            model_name='datosnuticionales',
            name='energia_kj',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Energía en Kj por 100g', max_digits=6),
        ),
        migrations.AlterField(
            model_name='datosnuticionales',
            name='grasas_saturadas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Grasas saturadas en g por 100g', max_digits=6),
        ),
        migrations.AlterField(
            model_name='datosnuticionales',
            name='grasas_totales',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Grasas totales en g por 100g', max_digits=6),
        ),
        migrations.AlterField(
            model_name='datosnuticionales',
            name='hidratosdecarbono',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Hidratos de carbono en g por 100g', max_digits=6),
        ),
        migrations.AlterField(
            model_name='datosnuticionales',
            name='proteinas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Proteinas en g por 100g', max_digits=6),
        ),
        migrations.AlterField(
            model_name='datosnuticionales',
            name='sal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Sal en g por 100g', max_digits=6),
        ),
    ]
