# Generated by Django 5.2.5 on 2025-09-19 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0013_alter_datosnuticionales_azucares_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosnuticionales',
            old_name='energia_kj',
            new_name='energia',
        ),
    ]
