# Generated by Django 5.2.5 on 2025-09-19 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0014_rename_energia_kj_datosnuticionales_energia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etiquetaplato',
            old_name='fibra',
            new_name='grasas_saturadas',
        ),
        migrations.RenameField(
            model_name='etiquetaplato',
            old_name='grasas',
            new_name='grasas_totales',
        ),
        migrations.RenameField(
            model_name='etiquetaplato',
            old_name='sal_mg',
            new_name='sal',
        ),
    ]
