# Generated by Django 5.2.6 on 2025-09-24 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0015_rename_fibra_etiquetaplato_grasas_saturadas_and_more'),
        ('super', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextoModo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super.centros')),
            ],
            options={
                'verbose_name': 'Texto de Modo de Empleo',
                'verbose_name_plural': 'Textos de Modo de Empleo',
            },
        ),
    ]
