# Generated by Django 5.2.6 on 2025-09-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0016_textomodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='textomodo',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
