# Generated by Django 5.2.6 on 2025-09-24 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0017_textomodo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='texto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='platos.textomodo'),
        ),
    ]
