# Generated by Django 5.2.6 on 2025-09-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0018_plato_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código único para el plato', max_length=10, unique=True),
        ),
    ]
