# Generated by Django 5.2.6 on 2025-09-29 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0020_alter_datosnuticionales_azucares_and_more'),
        ('super', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuticionalesSalsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energia', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('grasas_totales', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('grasas_saturadas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('hidratosdecarbono', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('azucares', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('proteinas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('sal', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super.centros')),
                ('salsa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutricion', to='platos.salsa')),
            ],
            options={
                'verbose_name': 'Datos Nutricionales',
                'verbose_name_plural': 'Datos Nutricionales',
            },
        ),
    ]
