# Generated by Django 5.2.6 on 2025-10-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0021_nuticionalessalsa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textomodo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
