# Generated by Django 5.2.6 on 2025-10-02 01:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('super', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('accion', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=100)),
                ('objeto_id', models.PositiveIntegerField()),
                ('objeto_repr', models.TextField()),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super.centros')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='super.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
