# Generated by Django 5.2.6 on 2025-10-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroaccion',
            name='cambios',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
