# Generated by Django 5.2.6 on 2025-10-03 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_registroaccion_cambios'),
        ('super', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'crear'), ('read', 'leer'), ('update', 'modificar'), ('delete', 'eliminar')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super.centros')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='super.userprofile')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'unique_together': {('perfil', 'content_type', 'action', 'centro')},
            },
        ),
    ]
