# Generated by Django 5.2.6 on 2025-10-03 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_permiso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permiso',
        ),
    ]
