# Generated by Django 5.0 on 2025-08-11 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('super', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergenos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('imagen', models.ImageField(blank=True, default='alergenos/default.jpg', null=True, upload_to='alergenos/')),
                ('estado', models.BooleanField(default=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super.centros')),
            ],
            options={
                'verbose_name': 'Alergeno',
                'verbose_name_plural': 'Alergenos',
                'unique_together': {('nombre', 'centro')},
            },
        ),
        migrations.CreateModel(
            name='Conservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('estado', models.BooleanField(default=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super.centros')),
            ],
            options={
                'verbose_name': 'Conservación',
                'verbose_name_plural': 'Conservaciones',
            },
        ),
        migrations.CreateModel(
            name='localizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacion', models.CharField(max_length=100, verbose_name='Localización')),
                ('estado', models.BooleanField(default=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super.centros')),
            ],
            options={
                'verbose_name': 'Localización',
                'verbose_name_plural': 'Localizaciones',
            },
        ),
        migrations.CreateModel(
            name='TipoAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('estado', models.BooleanField(default=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super.centros')),
            ],
            options={
                'verbose_name': 'Tipo Alimento',
                'verbose_name_plural': 'Tipos de Alimentos',
            },
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('nombre_alternativo', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', models.ImageField(blank=True, default='alimentos/default.jpg', null=True, upload_to='alimentos/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('stock_actual', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('alergenos', models.ManyToManyField(blank=True, to='dashuser.alergenos')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super.centros')),
                ('conservacion', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashuser.conservacion')),
                ('localizacion', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashuser.localizacion')),
                ('tipo_alimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashuser.tipoalimento')),
            ],
            options={
                'verbose_name': 'Alimento',
                'verbose_name_plural': 'Alimentos',
                'ordering': ['nombre'],
            },
        ),
    ]
