# Generated by Django 5.0 on 2025-08-12 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='stock_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='InformacionNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energia', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('carbohidratos', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('proteinas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('grasas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('azucares', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('sal_mg', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('acido_folico', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('vitamina_c', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('vitamina_a', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('zinc', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('hierro', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('calcio', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('colesterol', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('acidos_grasos_polinsaturados', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('acidos_grasos_monoinsaturados', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('acidos_grasos_saturados', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('fibra', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('alimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutricion', to='dashuser.alimento')),
            ],
        ),
    ]
