# Generated by Django 5.0 on 2025-08-12 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashuser', '0002_alter_alimento_stock_minimo_informacionnutricional'),
        ('super', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionnutricional',
            name='centro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='super.centros'),
            preserve_default=False,
        ),
    ]
