# Generated by Django 5.0 on 2025-08-12 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashuser', '0003_informacionnutricional_centro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacionnutricional',
            name='centro',
        ),
    ]
