# Generated by Django 5.0 on 2025-08-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashuser', '0005_unidaddemedida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionnutricional',
            name='sal_mg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7),
        ),
    ]
