# Generated by Django 5.0 on 2025-08-13 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashuser', '0006_alter_informacionnutricional_sal_mg'),
        ('super', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trazas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('imagen', models.ImageField(blank=True, default='trazas/default.jpg', null=True, upload_to='trazas/')),
                ('estado', models.BooleanField(default=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super.centros')),
            ],
            options={
                'verbose_name': 'Traza',
                'verbose_name_plural': 'Trazas',
                'unique_together': {('nombre', 'centro')},
            },
        ),
    ]
