# Generated by Django 5.2.5 on 2025-08-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashuser', '0007_trazas'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='trazas',
            field=models.ManyToManyField(blank=True, to='dashuser.trazas'),
        ),
    ]
