# Generated by Django 5.2.5 on 2025-09-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashuser', '0008_alimento_trazas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacionnutricional',
            name='acido_folico',
        ),
        migrations.RemoveField(
            model_name='informacionnutricional',
            name='acidos_grasos_monoinsaturados',
        ),
        migrations.RemoveField(
            model_name='informacionnutricional',
            name='acidos_grasos_polinsaturados',
        ),
        migrations.RemoveField(
            model_name='informacionnutricional',
            name='acidos_grasos_saturados',
        ),
        migrations.RemoveField(
            model_name='informacionnutricional',
            name='calcio',
        ),
        migrations.RemoveField(
            model_name='informacionnutricional',
            name='carbohidratos',
        ),
        migrations.RemoveField(
            model_name='informacionnutricional',
            name='colesterol',
        ),
        migrations.RemoveField(
            model_name='informacionnutricional',
            name='fibra',
        ),
        migrations.RemoveField(
            model_name='informacionnutricional',
            name='grasas',
        ),
        migrations.RemoveField(
            model_name='informacionnutricional',
            name='hierro',
        ),
        migrations.RemoveField(
            model_name='informacionnutricional',
            name='sal_mg',
        ),
        migrations.RemoveField(
            model_name='informacionnutricional',
            name='vitamina_a',
        ),
        migrations.RemoveField(
            model_name='informacionnutricional',
            name='vitamina_c',
        ),
        migrations.RemoveField(
            model_name='informacionnutricional',
            name='zinc',
        ),
        migrations.AddField(
            model_name='informacionnutricional',
            name='grasas_saturadas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Grasas saturadas en g por 100g', max_digits=6),
        ),
        migrations.AddField(
            model_name='informacionnutricional',
            name='grasas_totales',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Grasas totales en g por 100g', max_digits=6),
        ),
        migrations.AddField(
            model_name='informacionnutricional',
            name='hidratosdecarbono',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Hidratos de carbono en g por 100g', max_digits=6),
        ),
        migrations.AddField(
            model_name='informacionnutricional',
            name='sal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Sal en g por 100g', max_digits=6),
        ),
        migrations.AlterField(
            model_name='informacionnutricional',
            name='azucares',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Azúcares en g por 100g', max_digits=6),
        ),
        migrations.AlterField(
            model_name='informacionnutricional',
            name='energia',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Energía en Kj por 100g', max_digits=6),
        ),
        migrations.AlterField(
            model_name='informacionnutricional',
            name='proteinas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Proteinas en g por 100g', max_digits=6),
        ),
    ]
