# Generated by Django 5.2.6 on 2025-09-27 23:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashuser', '0009_remove_informacionnutricional_acido_folico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtiquetaAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=50)),
                ('fecha_caducidad', models.DateField()),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas', to='dashuser.alimento')),
            ],
        ),
    ]
