# Generated by Django 5.2.6 on 2025-09-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashuser', '0010_etiquetaalimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionnutricional',
            name='hidratosdecarbono',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Hidratos de carbono en g por 100g', max_digits=6, verbose_name='Hidratos de carbono'),
        ),
    ]
