# Generated by Django 5.2.6 on 2025-09-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashuser', '0011_alter_informacionnutricional_hidratosdecarbono'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='gtin',
            field=models.CharField(blank=True, help_text='Código GTIN del producto', max_length=14, null=True),
        ),
    ]
