# Generated by Django 5.2.6 on 2025-10-02 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashuser', '0012_alimento_gtin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='alergenos',
            field=models.ManyToManyField(blank=True, null=True, to='dashuser.alergenos'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='conservacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashuser.conservacion'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='localizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashuser.localizacion'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='stock_actual',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='stock_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='trazas',
            field=models.ManyToManyField(blank=True, null=True, to='dashuser.trazas'),
        ),
    ]
