# Generated by Django 5.2.6 on 2025-10-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashuser', '0013_alter_alimento_alergenos_alter_alimento_conservacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='alergenos',
            field=models.ManyToManyField(blank=True, to='dashuser.alergenos'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='trazas',
            field=models.ManyToManyField(blank=True, to='dashuser.trazas'),
        ),
    ]
