# Generated by Django 5.2.6 on 2025-10-05 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashuser', '0014_alter_alimento_alergenos_alter_alimento_trazas'),
        ('super', '0003_permiso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utensilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('gtin', models.CharField(blank=True, help_text='Código GTIN del producto', max_length=14, null=True)),
                ('imagen', models.ImageField(blank=True, default='utensilios/default.jpg', null=True, upload_to='utensilios/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_actual', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super.centros')),
                ('localizacion', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashuser.localizacion')),
            ],
            options={
                'verbose_name': 'Utensilio',
                'verbose_name_plural': 'Utensilios',
                'ordering': ['nombre'],
            },
        ),
    ]
