# Generated by Django 5.2.6 on 2025-10-06 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashuser', '0015_utensilio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utensilio',
            name='localizacion',
        ),
    ]
