# Generated by Django 5.2.6 on 2025-10-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashuser', '0016_remove_utensilio_localizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localizacion',
            name='localizacion',
        ),
        migrations.AddField(
            model_name='localizacion',
            name='nombre',
            field=models.CharField(default=1, max_length=100, verbose_name='Ubicación'),
            preserve_default=False,
        ),
    ]
