# Generated by Django 5.2.6 on 2025-10-17 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashuser', '0017_remove_localizacion_localizacion_localizacion_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='merma_uso',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='alimento',
            name='precio_medio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='alimento',
            name='unidad_compra',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='unidad_compra', to='dashuser.unidaddemedida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimento',
            name='unidad_uso',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='unidad_uso', to='dashuser.unidaddemedida'),
            preserve_default=False,
        ),
    ]
