# Generated by Django 5.2.6 on 2025-10-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashuser', '0018_alimento_merma_uso_alimento_precio_medio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimento',
            name='merma_uso',
        ),
        migrations.AddField(
            model_name='alimento',
            name='porcentaje_uso',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Porcentaje de uso'),
        ),
    ]
