# Generated by Django 5.2.6 on 2025-10-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashuser', '0019_remove_alimento_merma_uso_alimento_porcentaje_uso'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='peso_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Medida por unidad'),
        ),
    ]
