# Generated by Django 5.2.6 on 2025-10-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashuser', '0020_alimento_peso_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='stock_util',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
