# Generated by Django 5.2.6 on 2025-09-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre comercial')),
                ('razon_social', models.CharField(blank=True, max_length=200, verbose_name='Razón social')),
                ('cif_nif', models.CharField(blank=True, max_length=20, verbose_name='CIF/NIF')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código postal')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('provincia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia')),
                ('pais', models.CharField(default='España', max_length=100, null=True, verbose_name='País')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('web', models.URLField(blank=True, null=True, verbose_name='Sitio web')),
                ('persona_contacto', models.CharField(blank=True, max_length=150, null=True, verbose_name='Persona de contacto')),
                ('telefono_contacto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono de contacto')),
                ('activo', models.BooleanField(default=True, null=True, verbose_name='Proveedor activo')),
                ('fecha_alta', models.DateField(auto_now_add=True, verbose_name='Fecha de alta')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
    ]
