# Generated by Django 5.2.6 on 2025-09-28 19:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashuser', '0010_etiquetaalimento'),
        ('recepcion', '0002_proveedor_centro'),
        ('super', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(help_text='Número de lote del proveedor', max_length=50)),
                ('fecha_caducidad', models.DateField()),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad recibida (kg, L, etc.)', max_digits=10)),
                ('fecha_recepcion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='dashuser.alimento')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super.centros')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='recepcion.proveedor')),
            ],
            options={
                'verbose_name': 'Recepción',
                'verbose_name_plural': 'Recepciones',
                'ordering': ['-fecha_recepcion'],
            },
        ),
    ]
