# Generated by Django 5.2.6 on 2025-10-01 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashuser', '0012_alimento_gtin'),
        ('recepcion', '0003_recepcion'),
        ('super', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeMerma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Tipo de merma')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de merma',
                'verbose_name_plural': 'Tipos de mermas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Merma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad perdida')),
                ('unidad_medida', models.CharField(default='kg', max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mermas', to='dashuser.alimento')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super.centros')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mermas_registradas', to='super.userprofile')),
                ('tipo_merma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mermas', to='recepcion.tipodemerma')),
            ],
            options={
                'verbose_name': 'Merma',
                'verbose_name_plural': 'Mermas',
                'ordering': ['-fecha'],
            },
        ),
    ]
