# Generated by Django 5.2.6 on 2025-10-01 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0004_tipodemerma_merma'),
        ('super', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodemerma',
            name='centro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='super.centros'),
            preserve_default=False,
        ),
    ]
