# Generated by Django 5.2.6 on 2025-10-01 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashuser', '0012_alimento_gtin'),
        ('recepcion', '0005_tipodemerma_centro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merma',
            name='tipo_merma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recepcion.tipodemerma', verbose_name='Tipo de merma'),
        ),
        migrations.AlterField(
            model_name='merma',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashuser.unidaddemedida', verbose_name='Unidad de medida'),
        ),
    ]
