# Generated by Django 5.2.6 on 2025-10-01 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashuser', '0012_alimento_gtin'),
        ('recepcion', '0006_alter_merma_tipo_merma_alter_merma_unidad_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcion',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='unidad_medida',
            field=models.ForeignKey(default=1, help_text='Unidad de medida (kg, L, etc.)', on_delete=django.db.models.deletion.PROTECT, to='dashuser.unidaddemedida'),
            preserve_default=False,
        ),
    ]
