# Generated by Django 5.2.6 on 2025-10-06 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashuser', '0016_remove_utensilio_localizacion'),
        ('recepcion', '0007_recepcion_observaciones_recepcion_unidad_medida'),
        ('super', '0003_permiso'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_sistema', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('stock_real', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diferencia', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashuser.alimento')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super.centros')),
            ],
            options={
                'verbose_name': 'Ajuste de Inventario',
                'verbose_name_plural': 'Ajustes de Inventario',
                'ordering': ['-fecha'],
            },
        ),
    ]
