# Generated by Django 5.2.6 on 2025-10-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0008_ajusteinventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodemerma',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Tipo de merma'),
        ),
    ]
