# Generated by Django 5.2.6 on 2025-10-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0009_alter_tipodemerma_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recepcion',
            old_name='unidad_medida',
            new_name='unidad_compra',
        ),
        migrations.AddField(
            model_name='recepcion',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio compra'),
        ),
    ]
