# Generated by Django 5.2.6 on 2025-10-17 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0010_rename_unidad_medida_recepcion_unidad_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepcion',
            name='proveedor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='recepcion.proveedor'),
        ),
    ]
