# Generated by Django 5.0 on 2025-08-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('codigo_postal', models.CharField(blank=True, max_length=20, null=True, verbose_name='Codigo Postal')),
                ('pais', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pais')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('sitio_web', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sitio Web')),
                ('fecha_creacion', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('imagen', models.ImageField(blank=True, default='centro/default.png', null=True, upload_to='centros/')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Centro',
            },
        ),
    ]
